plugins {
    id 'com.android.application'
}

android {
    namespace = "com.cigarlounge.pos"
    compileSdk = 34

    defaultConfig {
        applicationId = "com.cigarlounge.pos"
        minSdk = 24
        targetSdk = 34
        versionCode = 1
        versionName = "1.0"
    }

    buildTypes {
        release {
            minifyEnabled = false
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidxwebkit:androidxwebkit:1.8.0'
    implementation 'androidx.activity:activity:1.8.0'
}
